[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.8.0",
    "pyqt5>=5.15.11",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
